services:
  - type: web
    name: tg-confession-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tg
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.9
